---
# ssh_users with sudo access
elevated_group_name: empowered
ssh_users:
  - user: "{{ master_user.username }}"
    key: "{{ master_user.key }}"

# oefenweb.fail2ban
fail2ban_ignoreips:
  - 127.0.0.1/8
  - 192.168.0.0/24
fail2ban_services:
  - name: sshd
    port: 22
    maxretry: 3
