---
# Elevated group name
elevated_group_name: empowered

# oefenweb.fail2ban
fail2ban_ignoreips:
  - 127.0.0.1/8
  - 192.168.0.0/24
fail2ban_services:
  - name: sshd
    port: 22
    maxretry: 3
    bantime: -1