---
# SSH Users
ssh_users:
  - user: "{{ master_user.username }}"
    key: "{{ master_user.key }}"

# Packages
setup_packages:
  - vim
  - git
  - htop
  - sudo
  - python3
  - python3-pip

# scrutiny-collector
scrutiny_collector_version: "0.3.12"
scrutiny_collector_platform: "linux-amd64"
scrutiny_collector_api_endpoint: "https://scrutiny.int.georgev.design"

# cloudalchemy.node_exporter
node_exporter_version: 1.2.0

#patrickjahns.promtail
promtail_version: 2.2.1
promtail_system_user: root
promtail_user_additional_groups: ""
promtail_loki_server_url: https://loki.int.georgev.design
promtail_config_scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: epsilon
          agent: promtail
          __path__: /var/log/*log
