---
# Packages
setup_packages:
  - vim
  - git
  - htop
  - sudo
  - python3
  - python3-pip

# dotfiles
dotfile_user: "{{ master_user.username }}"

# awesome-motd
motd_files:
  - src: 10-hostname-color
    name: 10-hostname-color
  - src: 20-sysinfo
    name: 20-sysinfo
  - src: 35-diskspace
    name: 35-diskspace

# cloudalchemy.node_exporter
node_exporter_version: 1.2.0

#patrickjahns.promtail
promtail_version: 2.2.1
promtail_system_user: root
promtail_user_additional_groups: ""
promtail_loki_server_url: https://loki.int.{{ vault_public_domain }}
promtail_config_scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: epsilon
          agent: promtail
          __path__: /var/log/*log
