---
# awesome-motd
motd_files:
  - src: 10-hostname-color
    name: 10-hostname-color
  - src: 20-sysinfo
    name: 20-sysinfo
  - src: 35-diskspace
    name: 35-diskspace
  - src: gamma/40-services
    name: 40-services
  - src: 60-docker
    name: 60-docker

# sysctl_props
inotify_max_user_watches: 524288

# Swap settings
swap_file_path: /swap.img
swap_file_state: absent

# Netplan setup
netplan_enabled: true
netplan_config_file: /etc/netplan/99-ansible-config.yaml
netplan_remove_existing: true
netplan_check_install: false
netplan_apply: true
netplan_configuration:
  network:
    version: 2
    ethernets:
      eno1:
        dhcp4: no
        addresses:
          - 192.168.0.202/24
        gateway4: 192.168.0.1
        nameservers:
          addresses: [8.8.8.8, 1.1.1.1]

# cloudalchemy.node_exporter
node_exporter_version: 1.2.0
node_exporter_disabled_collectors:
  - nvme

# textfile-collector
textfile_collector_scripts_directory_path: /opt/textfile_collector
textfile_collector_output_directory_path: /var/lib/node_exporter
textfile_collector_cron: "*/5 * * * *"

#patrickjahns.promtail
promtail_version: 2.2.1
promtail_system_user: root
promtail_user_additional_groups: ""
promtail_loki_server_url: https://loki.int.{{ vault_public_domain }}
promtail_config_scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: gamma
          agent: promtail
          __path__: /var/log/*log
      - targets:
          - localhost
        labels:
          job: backups
          host: gamma
          agent: promtail
          __path__: /var/log/backups/latest.log

# pakages-setup
packages_update: yes
setup_packages:
  - vim
  - git
  - htop
  - ctop
  - curl
  - zip
  - python3
  - python3-pip

# geerlingguy.docker
docker_edition: "ce"
docker_service_state: started
docker_service_enabled: true
docker_install_compose: true
docker_compose_version: "1.29.0"
docker_users:
  - "{{ master_user.username }}"
docker_daemon_options:
  dns: [8.8.4.4, 8.8.8.8]

# dir-skeleton
skeleton_dirs:
  - path: /home/{{ master_user.username }}/containers
    owner: "{{ master_user.username }}"
    group: "{{ master_user.username }}"
    mode: "750"

# ddclient
ddclient_PUID: "1000"
ddclient_PGID: "1000"
ddclient_TZ: "{{ master_user.timezone }}"
ddclient_volume: /home/{{ master_user.username }}/containers/managed/ddclient
ddclient_user: "{{ master_user.username }}"
ddclient_group: "{{ master_user.username }}"

# Borgmatic backups
backup_log_dir: /var/log/backups
backup_log_verbosity: 2
borgmatic_version: 1.5.15
backup_setup_cron: yes
backup_schedule: "0 */3 * * *"
borgmatic_configs:
  - name: containers
    location:
      source_dirs:
        - /home/{{ master_user.username }}/containers/main
      repositories:
        - "{{ vault_rsync_repo }}:backups/gamma_containers"
      exclude_patterns:
        - /home/{{ master_user.username }}/containers/main/bitwarden/icon_cache
      remote_executable: borg1
      exclude_caches: true
    storage:
      passphrase: "{{ vault_backups_passphrase }}"
    retention:
      keep_hourly: 12
      keep_daily: 5
    consistency:
      check_last: 2
    hooks:
      healthchecks: "{{ vault_backup_hc.gamma.docker }}"
