---
# Hostname config
custom_hostname: nimbus

# Static IP config
dhcp_config_static_ip: 192.168.0.200
dhcp_config_router_ip: 192.168.0.1
dhcp_config_dns_ip: 192.168.0.1

# Passwordless privileged users with ssh access with defined keys to be created
ssh_users:
  - user: "{{ master_user.username }}"
    key: "{{ master_user.key }}"

# User setup (will be made default)
default_user:
  username: "{{ master_user.username }}"
  groups:
      - adm
      - dialout
      - cdrom
      - sudo
      - audio
      - video
      - plugdev
      - games
      - users
      - input
      - netdev
      - gpio
      - i2c
      - spi

# awesome-motd
motd_files:
  - src: 10-hostname-color
    name: 10-hostname-color
  - src: 20-sysinfo
    name: 20-sysinfo
  - src: 35-diskspace
    name: 35-diskspace
  - src: 60-docker
    name: 60-docker

# Packages to be installed during setup
setup_packages:
  - vim
  - git
  - htop
  - curl
  - zip
  - python3
  - python3-setuptools
  - python3-pip
  - libffi-dev

# Containers vars
containers_dir: "/home/{{ master_user.username }}/containers"
containers_managed_dir: "{{ containers_dir }}/_managed"
containers_user: "{{ master_user.username }}"
containers_group: "{{ master_user.username }}"