---
# pakages-setup
packages_update: yes
setup_packages:
  - vim
  - git
  - htop
  - ctop
  - curl
  - zip
  - python3
  - python3-pip

# sysctl_props
inotify_max_user_watches: 524288

# Netplan setup
netplan_enabled: true
netplan_config_file: /etc/netplan/99-ansible-config.yaml
netplan_remove_existing: true
netplan_check_install: false
netplan_apply: true
netplan_configuration:
  network:
    version: 2
    ethernets:
      ens18:
        dhcp4: no
        addresses:
          - 192.168.0.205/24
        gateway4: 192.168.0.1
        nameservers:
          addresses: [8.8.8.8, 1.1.1.1]

# dotfiles
dotfile_user: "{{ master_user.username }}"

# awesome-motd
motd_files:
  - src: 10-hostname-color
    name: 10-hostname-color
  - src: 20-sysinfo
    name: 20-sysinfo
  - src: 35-diskspace
    name: 35-diskspace
  - src: 60-docker
    name: 60-docker

# geerlingguy.docker
docker_edition: "ce"
docker_service_state: started
docker_service_enabled: true
docker_install_compose: true
docker_users:
  - "{{ master_user.username }}"
