---
# IP used for connection
ansible_ssh_host: "{{ vault_roberto_ip }}"

# pakages-setup
packages_update: yes
setup_packages:
  - vim
  - git
  - htop
  - ctop
  - curl
  - zip
  - python3
  - python3-pip

# awesome-motd
motd_files:
  - src: 10-hostname-color
    name: 10-hostname-color
  - src: 20-sysinfo
    name: 20-sysinfo
  - src: 35-diskspace
    name: 35-diskspace
  - src: 60-docker
    name: 60-docker

# geerlingguy.docker
docker_edition: "ce"
docker_service_state: started
docker_service_enabled: true
docker_install_compose: true
docker_users:
  - "{{ master_user.username }}"
