---
- hosts: epsilon
  become: yes
  
  tasks:
    - name: Update authorized keys
      authorized_key:
        user: "{{ item.user }}"
        key: "{{ item.key }}"
        exclusive: yes
        state: present
      loop: "{{ ssh_users }}"