---
# This will provision a fresh Proxmox instance with user in order
# to be able to run the main playbook on it
# This playbook is meant to be run using the root user
# sshpass package might be needed on local machine

# Tested on Proxmox 7, might need edits for other versions
- hosts: proxmox
  become: true
  pre_tasks:
    - name: Remove enterprise repository file
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent

    - name: Add no subscription community repository
      ansible.builtin.apt_repository:
        repo: deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
        filename: pve-no-subscription
        state: present
  roles:
    - role: packages_setup
      tags: packages
    - role: ssh_users
      tags: ssh_users
