roles:
  - name: geerlingguy.docker
    version: 2.8.1
  - name: oefenweb.fail2ban
    version: v3.3.13

collections:
  - name: ansible.posix
    version: 1.2.0
  - name: community.general
    version: 3.3.0
  