---
- hosts: epsilon
  become: yes
  vars_files:
    - vars/vault.yml
  roles:
    - role: packages-setup
    - role: geerlingguy.ntp
    - role: oefenweb.fail2ban
    - role: create-users
    - role: geerlingguy.docker
    - role: epsilon
    - role: awesome-motd
    - role: backups

- hosts: gamma
  become: yes
  roles:
    - role: packages-setup
    - role: geerlingguy.docker
    - role: oefenweb.fail2ban
    - role: create-users
    - role: awesome-motd
    - role: dir-skeleton
    - role: ssh-protect