---
- hosts: epsilon
  become: yes
  vars_files:
    - vars/vault.yml
  roles:
    - role: packages_setup
    - role: cloudalchemy.node_exporter
    - role: patrickjahns.promtail

- hosts: apollo
  become: yes
  vars_files:
    - vars/vault.yml
  roles:
    - role: packages_setup
    - role: geerlingguy.docker
    - role: storage_setup
    - role: snapraid
    - role: samba
    - role: dir_skeleton
    - role: awesome_motd
    - role: cloudalchemy.node_exporter
    - role: patrickjahns.promtail
    - role: textfile_collector
    - role: adguardhome_prep
    - role: dns_setup
    - role: backups

- hosts: gamma
  become: yes
  vars_files:
    - vars/vault.yml
  roles:
    - role: packages_setup
    - role: geerlingguy.docker
    - role: ddclient
    - role: oefenweb.fail2ban
    - role: awesome_motd
    - role: dir_skeleton
    - role: cloudalchemy.node_exporter
    - role: textfile_collector
    - role: patrickjahns.promtail
    - role: adguardhome_prep
    - role: dns_setup
    - role: backups