---
- hosts: all
  become: true
  vars_files:
    - vars/vault.yml
  roles:
    - role: packages_setup
      tags: packages
    - role: node_exporter
      tags: node_exporter
    - role: patrickjahns.promtail
      tags: promtail
    - role: awesome_motd
      tags: motd
    - role: dotfiles
      tags: dotfiles

- hosts: ubuntu
  become: true
  vars_files:
    - vars/vault.yml
  roles:
    - role: snapbegone
      tags: snap
    - role: geerlingguy.swap
      tags: swap
    - role: dns_setup
      tags: dns
    - role: netplan
      tags: netplan
    - role: geerlingguy.docker
      tags: docker
    - role: swarm
      tags: swarm
    - role: dir_skeleton
      tags: skeleton
    - role: textfile_collector
      tags: textfile_collector
    - role: adguardhome_prep
      tags: adguard_prep
    - role: backups
      tags: backups

- hosts: apollo
  become: true
  vars_files:
    - vars/vault.yml
  roles:
    - role: nvidia_gpu
      tags: gpu
    - role: storage_setup
      tags: storage
    - role: snapraid
      tags: snapraid
    - role: samba
      tags: samba

- hosts: gamma
  become: true
  vars_files:
    - vars/vault.yml
  roles:
    - role: ddclient
      tags: ddclient
