---
- hosts: epsilon
  become: yes
  vars_files:
    - vars/vault.yml
  roles:
    - role: packages-setup
    - role: create-users
    - role: scrutiny-collector
    - role: ssh-protect

- hosts: apollo
  become: yes
  vars_files:
    - vars/vault.yml
  roles:
    - role: packages-setup
    - role: oefenweb.fail2ban
    - role: create-users
    - role: geerlingguy.docker
    - role: storage-setup
    - role: samba
    - role: awesome-motd
    - role: dir-skeleton
    - role: backups

- hosts: gamma
  become: yes
  vars_files:
    - vars/vault.yml
  roles:
    - role: packages-setup
    - role: geerlingguy.docker
    - role: ddclient
    - role: oefenweb.fail2ban
    - role: create-users
    - role: awesome-motd
    - role: dir-skeleton
    - role: ssh-protect
    - role: backups