---
- name: Install smartmontools
  apt:
    name: smartmontools
    state: present
  
- name: Create target directory
  file:
    path: "/opt/scrutiny/scrutiny_collector_{{ scrutiny_collector_version }}"
    state: directory

- name: Download and extract Node Exporter binary
  get_url:
    url: https://github.com/AnalogJ/scrutiny/releases/download/{{ scrutiny_collector_version }}/scrutiny-collector-metrics-{{ scrutiny_collector_platform }}
    dest: "/opt/scrutiny/scrutiny_collector_{{ scrutiny_collector_version }}/scrutiny-collector"
    mode: "0740"

- name: Create symlink to correct binary
  ansible.builtin.file:
    src: "/opt/scrutiny/scrutiny_collector_{{ scrutiny_collector_version }}/scrutiny-collector"
    dest: "/opt/scrutiny/collector"
    owner: "root"
    group: "root"
    state: link

- name: Set correct permissions
  file:
    path: "/opt/scrutiny"
    state: directory
    recurse: yes
    owner: "root"
    group: "root"
    mode: "0755"

- name: Create cron file under /etc/cron.d for collector
  ansible.builtin.cron:
    name: "scrutiny collector"
    minute: "0"
    hour: "0"
    user: root
    job: /opt/scrutiny/collector run --api-endpoint {{ scrutiny_collector_api_endpoint | quote }}
    cron_file: ansible__scrutiny_collector

- name: Run collector to populate data
  ansible.builtin.shell: "/opt/scrutiny/collector run --api-endpoint {{ scrutiny_collector_api_endpoint | quote }}"
