---
- name: Create mount points
  file:
    path: "{{ item.path }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: "777"
  loop: "{{ data_disks }}"

- name: Mount disks
  mount:
    path: "{{ item.path }}"
    src: "{{ item.id }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    state: present
  loop: "{{ data_disks }}"

- name: Install MergerFS
  apt:
    name: mergerfs
    state: present

- name: Create mount point for MergerFS
  file:
    path: "{{ mergerfs_mount.dest }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: "777"

- name: Mount MergerFS
  mount:
    path: "{{ mergerfs_mount.dest }}"
    src: "{{ mergerfs_mount.src }}"
    fstype: "{{ mergerfs_mount.fs }}"
    opts: "{{ mergerfs_mount.opts }}"
    state: present
  