---
- name: Install docker pip module
  pip:
    name: docker
    state: present

- name: Run ddclient container
  docker_container:
    name: ddclient
    image: linuxserver/ddclient
    state: started
    container_default_behavior: compatibility
    dns_servers:
      - 8.8.8.8
      - 1.1.1.1
    env:
      PUID: "{{ ddclient_docker_uid }}"
      PGID: "{{ ddclient_docker_gid }}"
      TZ: "{{ ddclient_docker_tz }}"
    volumes:
      - "{{ ddclient_volume }}:/config"
    restart_policy: unless-stopped

- name: Provision ddclient config file
  template:
    src: "ddclient.j2"
    dest: "{{ ddclient_volume }}/ddclient.conf"
    owner: "{{ ddclient_user }}"
    group: "{{ ddclient_group }}"
    mode: 0644
  notify: restart ddclient container
