---
- name: Install SMB
  ansible.builtin.apt:
    name: samba
    state: present

- name: Update SMB config
  ansible.builtin.template:
    src: smb.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644

- name: Restart and enable SMB
  ansible.builtin.service:
    name: smbd
    enabled: yes
    state: started

- name: Show reminder
  ansible.builtin.debug:
    msg: "Don't forget to also create the users and run smbpasswd"

# TODO: Add way to also add users
# adduser -s /sbin/nologin -h /home/samba -H -D user
# smbpasswd -a user
