---
- name: Create /mnt points
  file:
    path: "{{ item.path }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: "777"
  loop: "{{ data_disks }}"

- name: Mount disks
  mount:
    path: "{{ item.path }}"
    src: "{{ item.id }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    state: present
  loop: "{{ data_disks }}"

- name: Install MergerFS
  apt:
    name: mergerfs
    state: present

- name: Create /mnt points for MergerFS
  file:
    path: "{{ item.dest }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: "777"
  loop: "{{ mergerfs_mounts }}"

- name: Mount MergerFS array
  mount:
    path: "{{ item.dest }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    state: present
  loop: "{{ mergerfs_mounts }}"
  