---
- name: Check if Docker is already present.
  command: which docker
  failed_when: false
  changed_when: false
  register: docker_command_result

- name: Download Docker install convenience script.
  get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: 0775
  when: docker_command_result.rc == 1

- name: Run Docker install convenience script.
  command: /tmp/get-docker.sh
  environment:
    CHANNEL: stable
  when: docker_command_result.rc == 1

- name: Make sure Docker CE package is present.
  apt:
    name: "docker-ce"
    state: present
    force: true
    install_recommends: no

- name: Ensure Docker is started.
  service:
    name: docker
    state: started
    enabled: true

- name: Ensure docker can be used by the default user.
  user:
    name: "{{ default_user.username }}"
    groups: docker
    append: true

- name: Check if Docker Compose is already present.
  command: which docker-compose
  failed_when: false
  changed_when: false
  register: docker_compose_result

- name: Download docker-compose to bin path.
  command: sudo curl -L "https://github.com/docker/compose/releases/download/1.27.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  when: docker_compose_result.rc == 1

- name: Make docker-compose executable.
  command: sudo chmod +x /usr/local/bin/docker-compose
  when: docker_compose_result.rc == 1