---
- name: Disable SSH password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  register: ssh_config

- name: Reboot machine to reload SSH if config changed
  reboot:
    reboot_timeout: 600
  when: ssh_config.changed