---
- name: Install resolvconf
  ansible.builtin.apt:
    name: resolvconf
    state: present
    update_cache: true

- name: Enable resolvconf service
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: resolvconf

- name: Update config
  ansible.builtin.copy:
    src: head
    dest: /etc/resolvconf/resolv.conf.d/head
    mode: "0644"

- name: Update resolv.conf
  ansible.builtin.command: "resolvconf -u"
