---
- name: Create swarm
  community.docker.docker_swarm:
    state: present
  register: swarm_manager

- name: Set join token fact
  ansible.builtin.set_fact:
    swarm_worker_token: "{{ swarm_manager.swarm_facts.JoinTokens.Worker }}"

- name: Show worker join token
  ansible.builtin.debug:
    msg: "Token to join as a worker: {{ swarm_worker_token }}"

- name: Create overlay network
  community.docker.docker_network:
    name: "{{ swarm_network_name }}"
    driver: overlay
    attachable: true
  when: swarm_create_network
