---
- name: Configuring Netplan
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ netplan_config_file }}"
    mode: 0644
  become: true
  when: netplan_configuration != []
  notify: netplan generate config
