---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - figlet
      - lolcat
    state: present

- name: Remove all files in /etc/update-motd.d
  ansible.builtin.file:
    path: /etc/update-motd.d
    state: absent

- name: Recreate directory /etc/update-motd.d
  ansible.builtin.file:
    path: /etc/update-motd.d
    state: directory
    mode: '755'

- name: Copy motd files
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: /etc/update-motd.d/{{ item.name }}
    mode: '755'
  loop: '{{ motd_files }}'
