---
- name: check valid configuration
  block:
    - name: Fail if no data disks are defined
      fail:
        msg: No data disks defined
      when: snapraid_data_disks | length == 0

    - name: Fail if no parity disks are defined
      fail:
        msg: No parity disks defined
      when: snapraid_parity_disks | length == 0

    - name: Fail if no content is defined
      fail:
        msg: No content files defined
      when:
        - snapraid_content_files | length == 0
        - snapraid_data_disks | selectattr('content') | length == 0
        - snapraid_parity_disks | selectattr('content') | length == 0

- name: install snapraid config file
  template:
    src: snapraid.conf.j2
    dest: /etc/snapraid.conf
    owner: root
    group: root
    mode: 0775
