---
- name: Create skeleton directory
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default(skeleton_default_owner) }}"
    group: "{{ item.group | default(skeleton_default_group) }}"
    mode: "{{ item.mode | default(omit) | quote }}"
    recurse: "{{ item.recurse | default(false) | bool }}"
  loop: "{{ skeleton_dirs }}"
  loop_control:
    label: "{{ item.path }}"
