---
# defaults file for ansible-netplan
netplan_config_file: /etc/netplan/ansible-config.yaml

# switch to enable/disable the role completely
netplan_enabled: true

# Configured devices get handled by systemd-networkd by default, unless explicitly marked as managed by a specific renderer (NetworkManager)
netplan_renderer:

netplan_configuration: {}
netplan_remove_existing: true
netplan_check_install: true
netplan_apply: true
netplan_packages:
  - nplan
  - netplan.io
